# Generated by Django 4.2.7 on 2023-11-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('summary', models.CharField(max_length=500)),
                ('image', models.URLField(null=True)),
                ('query', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-image', '-id'],
            },
        ),
    ]
