# Generated by Django 4.2.7 on 2023-11-25 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_wiki_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki',
            name='user',
        ),
        migrations.AddField(
            model_name='wiki',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
